import json
from datetime import timedelta


def calcula_horario_atividade(rotina, atividades):
    horario = timedelta(0)

    for u in rotina:
        horario += timedelta(minutes=atividades[u.capitalize()]["duracao"])
    return horario


with open('./rotinas/Cenario_validacao_Artigo(1usuarios-casa-mayki).json') as json_file:
    dados = json.load(json_file)
    rotina_dia = ["USAR_PC_MADRUGADA_INICIO_DOM", "DORMIR_FIM_SEM", "ESCOVAR_DENTE", "USAR_PC_MANHA_FIM_SEM", "SAIR_COMODO_60M", "SAIR_COMODO_60M", "SAIR_COMODO_60M", "SAIR_COMODO_60M", "SAIR_COMODO_60M","SAIR_COMODO_60M", "USAR_PC_NOITE_FIM_SEM", "USAR_PC_NOITE_FIM_SEM", "USAR_PC_NOITE_FIM_SEM", "USAR_PC_NOITE_FIM_DOM"]


    horario = calcula_horario_atividade(rotina_dia, dados['ATIVIDADES'])

    print(horario)

# Segunda-feira
# ["USAR_PC_MADRUGADA_INICIO", "USAR_PC_NOITE","FAZER_NADA_NOITE", "DORMIR", "ESCOVAR_DENTE", "PREPARAR_CAFE_DA_MANHA", "USAR_PC_MANHA", "USAR_PC_MANHA", "FAZER_NADA_DIA", "SAIR_COMODO_01", "SAIR_COMODO_01", "SAIR_COMODO_01", "SAIR_COMODO_01","SAIR_COMODO_01", "SAIR_COMODO_01", "SAIR_COMODO_01", "SAIR_COMODO_02", "SAIR_COMODO_02", "FAZER_NADA_NOITE", "USAR_PC_NOITE", "USAR_PC_NOITE", "USAR_PC_NOITE_FIM"]
# Terça-feira
# ["USAR_PC_MADRUGADA_30M_INICIO", "DORMIR", "DORMIR_30M", "DORMIR_30M", "DORMIR_30M", "DORMIR_30M", "ESCOVAR_DENTE", "PREPARAR_CAFE_DA_MANHA", "FAZER_NADA_DIA", "SAIR_COMODO_60M", "SAIR_COMODO_60M", "SAIR_COMODO_60M", "SAIR_COMODO_60M","SAIR_COMODO_60M", "SAIR_COMODO_60M", "SAIR_COMODO_60M", "SAIR_COMODO_60M", "SAIR_COMODO_60M", "SAIR_COMODO_10M", "SAIR_COMODO_10M", "FAZER_NADA_NOITE", "USAR_PC_NOITE", "USAR_PC_NOITE", "USAR_PC_NOITE_FIM"]
# Quarta-feira
# ["DORMIR","DORMIR_30M","DORMIR_30M","DORMIR_30M","DORMIR_30M","DORMIR_30M", "ESCOVAR_DENTE","USAR_PC_MANHA_30M", "PREPARAR_CAFE_DA_MANHA", "USAR_PC_MANHA", "FAZER_NADA_DIA", "SAIR_COMODO_60M", "SAIR_COMODO_60M", "SAIR_COMODO_60M", "SAIR_COMODO_60M", "SAIR_COMODO_60M","SAIR_COMODO_60M", "SAIR_COMODO_60M", "SAIR_COMODO_60M", "SAIR_COMODO_10M", "SAIR_COMODO_10M", "SAIR_COMODO_10M", "SAIR_COMODO_10M", "FAZER_NADA_NOITE", "USAR_PC_NOITE", "USAR_PC_NOITE", "USAR_PC_NOITE_FIM"]
# Quinta-feira
# ["DORMIR","DORMIR_30M","DORMIR_30M","DORMIR_30M","DORMIR_30M", "ESCOVAR_DENTE", "USAR_PC_MANHA_30M", "FAZER_NADA_DIA", "SAIR_COMODO_60M", "SAIR_COMODO_60M", "SAIR_COMODO_60M", "SAIR_COMODO_60M","SAIR_COMODO_60M", "SAIR_COMODO_60M", "SAIR_COMODO_60M", "SAIR_COMODO_10M", "SAIR_COMODO_10M", "SAIR_COMODO_10M", "FAZER_NADA_NOITE", "USAR_PC_NOITE", "USAR_PC_NOITE", "USAR_PC_NOITE_FIM"]
# Sexta-feira
# ["USAR_PC_MADRUGADA_INICIO","DORMIR","DORMIR_30M","DORMIR_30M","DORMIR_30M", "ESCOVAR_DENTE", "FAZER_NADA_DIA", "FAZER_NADA_DIA", "SAIR_COMODO_60M", "SAIR_COMODO_60M", "SAIR_COMODO_60M", "SAIR_COMODO_60M", "SAIR_COMODO_60M", "SAIR_COMODO_60M", "SAIR_COMODO_60M", "SAIR_COMODO_60M", "SAIR_COMODO_10M", "SAIR_COMODO_10M", "SAIR_COMODO_10M", "FAZER_NADA_NOITE", "USAR_PC_NOITE", "USAR_PC_NOITE", "USAR_PC_NOITE_FIM"]
# Sabado
# ["USAR_PC_MADRUGADA_INICIO", "USAR_PC_NOITE_30M", "DORMIR_FIM_SEM","DORMIR_30M", "FAZER_NADA_DIA", "ESCOVAR_DENTE", "USAR_PC_MANHA", "USAR_PC_MANHA", "USAR_PC_MANHA", "USAR_PC_MANHA","USAR_PC_MANHA","USAR_PC_MANHA","USAR_PC_MANHA","USAR_PC_MANHA","USAR_PC_MANHA", "USAR_PC_NOITE_FIM"]
# Domingo
# ["USAR_PC_MADRUGADA_INICIO", "USAR_PC_NOITE_30M", "DORMIR_FIM_SEM", "ESCOVAR_DENTE", "USAR_PC_MANHA_FIM_SEM", "USAR_PC_MANHA_FIM_SEM", "SAIR_COMODO_60M", "USAR_PC_MANHA_FIM_SEM", "USAR_PC_MANHA_FIM_SEM", "USAR_PC_MANHA", "SAIR_COMODO_60M", "USAR_PC_MANHA_FIM_SEM"]
